### ISSUE TITLE
Only detecting class and first card choice, stops detecting afterwards

### ISSUE THREAD

**Issue by HCICZX** [rembound/Arena-Helper#101] opened 2016-09-11 04:01 UTC
First 3 cards are Stampeding Kodo, Muster for Battle and Master Jouster, but next 3 cards were not detected. http://i.imgur.com/s9kdKgj.jpg

**Comment by rembound** [comment] 2016-09-14 07:39
Thanks for the report. Should be fixed in next version.

**Comment by rembound** [comment] 2016-09-16 14:01
Made is more reliable in the new version.

**Closed by rembound** 2016-09-16 14:01 UTC

**Comment by nicolasdalsass** [comment] 2016-09-16 18:37
I think what happens is it trigger the next card detection to fast when a card is selected, and it's still able to see the old cards. Tbh, I think a small manual "redetect" button (e.g where the grey square for manual hero picking is) would do wonder :) Still a great plugin !

**Comment by rembound** [comment] 2016-09-16 19:10
Yeah, the old cards are getting re-detected. I've modified it so that when it detects the same cards, it needs to detect these cards multiple times in a row. When different cards are detected, it just continues as normal.

**Comment by nicolasdalsass** [comment] 2016-09-16 22:02
Yeah, I saw the fix, but I don't think it's working as intended since the triple loop still seems to happen too fast, and the 3 detections can end before the new cards appear. I guess a Thread.sleep(3 seconds) between the loop could work too, but I don't know the language to PR it :/

**Comment by rembound** [comment] 2016-09-17 09:53
Will add a timed delay with a maximum for the next update.
